# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.design_allocation import DesignAllocation
from openapi_client.models.design_time_perspective import DesignTimePerspective
from openapi_client.models.interventional_assignment import InterventionalAssignment
from openapi_client.models.masking_block import MaskingBlock
from openapi_client.models.observational_model import ObservationalModel
from openapi_client.models.primary_purpose import PrimaryPurpose
from typing import Optional, Set
from typing_extensions import Self

class DesignInfo(BaseModel):
    """
    DesignInfo
    """ # noqa: E501
    allocation: Optional[DesignAllocation] = None
    intervention_model: Optional[InterventionalAssignment] = Field(default=None, alias="interventionModel")
    intervention_model_description: Optional[StrictStr] = Field(default=None, alias="interventionModelDescription")
    primary_purpose: Optional[PrimaryPurpose] = Field(default=None, alias="primaryPurpose")
    observational_model: Optional[ObservationalModel] = Field(default=None, alias="observationalModel")
    time_perspective: Optional[DesignTimePerspective] = Field(default=None, alias="timePerspective")
    masking_info: Optional[MaskingBlock] = Field(default=None, alias="maskingInfo")
    __properties: ClassVar[List[str]] = ["allocation", "interventionModel", "interventionModelDescription", "primaryPurpose", "observationalModel", "timePerspective", "maskingInfo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DesignInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of masking_info
        if self.masking_info:
            _dict['maskingInfo'] = self.masking_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DesignInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allocation": obj.get("allocation"),
            "interventionModel": obj.get("interventionModel"),
            "interventionModelDescription": obj.get("interventionModelDescription"),
            "primaryPurpose": obj.get("primaryPurpose"),
            "observationalModel": obj.get("observationalModel"),
            "timePerspective": obj.get("timePerspective"),
            "maskingInfo": MaskingBlock.from_dict(obj["maskingInfo"]) if obj.get("maskingInfo") is not None else None
        })
        return _obj


