# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.sampling_method import SamplingMethod
from openapi_client.models.sex import Sex
from openapi_client.models.standard_age import StandardAge
from typing import Optional, Set
from typing_extensions import Self

class EligibilityModule(BaseModel):
    """
    EligibilityModule
    """ # noqa: E501
    eligibility_criteria: Optional[StrictStr] = Field(default=None, alias="eligibilityCriteria")
    healthy_volunteers: Optional[StrictBool] = Field(default=None, alias="healthyVolunteers")
    sex: Optional[Sex] = None
    gender_based: Optional[StrictBool] = Field(default=None, alias="genderBased")
    gender_description: Optional[StrictStr] = Field(default=None, alias="genderDescription")
    minimum_age: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="minimumAge")
    maximum_age: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="maximumAge")
    std_ages: Optional[List[StandardAge]] = Field(default=None, alias="stdAges")
    study_population: Optional[StrictStr] = Field(default=None, alias="studyPopulation")
    sampling_method: Optional[SamplingMethod] = Field(default=None, alias="samplingMethod")
    __properties: ClassVar[List[str]] = ["eligibilityCriteria", "healthyVolunteers", "sex", "genderBased", "genderDescription", "minimumAge", "maximumAge", "stdAges", "studyPopulation", "samplingMethod"]

    @field_validator('minimum_age')
    def minimum_age_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$", value):
            raise ValueError(r"must validate the regular expression /^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$/")
        return value

    @field_validator('maximum_age')
    def maximum_age_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$", value):
            raise ValueError(r"must validate the regular expression /^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EligibilityModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EligibilityModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eligibilityCriteria": obj.get("eligibilityCriteria"),
            "healthyVolunteers": obj.get("healthyVolunteers"),
            "sex": obj.get("sex"),
            "genderBased": obj.get("genderBased"),
            "genderDescription": obj.get("genderDescription"),
            "minimumAge": obj.get("minimumAge"),
            "maximumAge": obj.get("maximumAge"),
            "stdAges": obj.get("stdAges"),
            "studyPopulation": obj.get("studyPopulation"),
            "samplingMethod": obj.get("samplingMethod")
        })
        return _obj


