# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.list_size import ListSize
from typing import Optional, Set
from typing_extensions import Self

class ListSizes(BaseModel):
    """
    ListSizes
    """ # noqa: E501
    var_field: StrictStr = Field(alias="field")
    max_size: Optional[StrictInt] = Field(default=None, alias="maxSize")
    min_size: Optional[StrictInt] = Field(default=None, alias="minSize")
    piece: StrictStr
    top_sizes: Optional[List[ListSize]] = Field(default=None, alias="topSizes")
    unique_sizes_count: StrictInt = Field(alias="uniqueSizesCount")
    __properties: ClassVar[List[str]] = ["field", "maxSize", "minSize", "piece", "topSizes", "uniqueSizesCount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListSizes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in top_sizes (list)
        _items = []
        if self.top_sizes:
            for _item_top_sizes in self.top_sizes:
                if _item_top_sizes:
                    _items.append(_item_top_sizes.to_dict())
            _dict['topSizes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListSizes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "field": obj.get("field"),
            "maxSize": obj.get("maxSize"),
            "minSize": obj.get("minSize"),
            "piece": obj.get("piece"),
            "topSizes": [ListSize.from_dict(_item) for _item in obj["topSizes"]] if obj.get("topSizes") is not None else None,
            "uniqueSizesCount": obj.get("uniqueSizesCount")
        })
        return _obj


