# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.certain_agreement import CertainAgreement
from openapi_client.models.limitations_and_caveats import LimitationsAndCaveats
from openapi_client.models.point_of_contact import PointOfContact
from typing import Optional, Set
from typing_extensions import Self

class MoreInfoModule(BaseModel):
    """
    MoreInfoModule
    """ # noqa: E501
    limitations_and_caveats: Optional[LimitationsAndCaveats] = Field(default=None, alias="limitationsAndCaveats")
    certain_agreement: Optional[CertainAgreement] = Field(default=None, alias="certainAgreement")
    point_of_contact: Optional[PointOfContact] = Field(default=None, alias="pointOfContact")
    __properties: ClassVar[List[str]] = ["limitationsAndCaveats", "certainAgreement", "pointOfContact"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MoreInfoModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of limitations_and_caveats
        if self.limitations_and_caveats:
            _dict['limitationsAndCaveats'] = self.limitations_and_caveats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of certain_agreement
        if self.certain_agreement:
            _dict['certainAgreement'] = self.certain_agreement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of point_of_contact
        if self.point_of_contact:
            _dict['pointOfContact'] = self.point_of_contact.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MoreInfoModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "limitationsAndCaveats": LimitationsAndCaveats.from_dict(obj["limitationsAndCaveats"]) if obj.get("limitationsAndCaveats") is not None else None,
            "certainAgreement": CertainAgreement.from_dict(obj["certainAgreement"]) if obj.get("certainAgreement") is not None else None,
            "pointOfContact": PointOfContact.from_dict(obj["pointOfContact"]) if obj.get("pointOfContact") is not None else None
        })
        return _obj


