# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.avail_ipd import AvailIpd
from openapi_client.models.reference import Reference
from openapi_client.models.see_also_link import SeeAlsoLink
from typing import Optional, Set
from typing_extensions import Self

class ReferencesModule(BaseModel):
    """
    ReferencesModule
    """ # noqa: E501
    references: Optional[List[Reference]] = None
    see_also_links: Optional[List[SeeAlsoLink]] = Field(default=None, alias="seeAlsoLinks")
    avail_ipds: Optional[List[AvailIpd]] = Field(default=None, alias="availIpds")
    __properties: ClassVar[List[str]] = ["references", "seeAlsoLinks", "availIpds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReferencesModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in references (list)
        _items = []
        if self.references:
            for _item_references in self.references:
                if _item_references:
                    _items.append(_item_references.to_dict())
            _dict['references'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in see_also_links (list)
        _items = []
        if self.see_also_links:
            for _item_see_also_links in self.see_also_links:
                if _item_see_also_links:
                    _items.append(_item_see_also_links.to_dict())
            _dict['seeAlsoLinks'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in avail_ipds (list)
        _items = []
        if self.avail_ipds:
            for _item_avail_ipds in self.avail_ipds:
                if _item_avail_ipds:
                    _items.append(_item_avail_ipds.to_dict())
            _dict['availIpds'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReferencesModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "references": [Reference.from_dict(_item) for _item in obj["references"]] if obj.get("references") is not None else None,
            "seeAlsoLinks": [SeeAlsoLink.from_dict(_item) for _item in obj["seeAlsoLinks"]] if obj.get("seeAlsoLinks") is not None else None,
            "availIpds": [AvailIpd.from_dict(_item) for _item in obj["availIpds"]] if obj.get("availIpds") is not None else None
        })
        return _obj


