# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.date_struct import DateStruct
from openapi_client.models.expanded_access_info import ExpandedAccessInfo
from openapi_client.models.partial_date_struct import PartialDateStruct
from openapi_client.models.status import Status
from typing import Optional, Set
from typing_extensions import Self

class StatusModule(BaseModel):
    """
    StatusModule
    """ # noqa: E501
    status_verified_date: Optional[StrictStr] = Field(default=None, description="Date in `yyyy`, `yyyy-MM`, or `yyyy-MM-dd` format", alias="statusVerifiedDate")
    overall_status: Optional[Status] = Field(default=None, alias="overallStatus")
    last_known_status: Optional[Status] = Field(default=None, alias="lastKnownStatus")
    delayed_posting: Optional[StrictBool] = Field(default=None, alias="delayedPosting")
    why_stopped: Optional[StrictStr] = Field(default=None, alias="whyStopped")
    expanded_access_info: Optional[ExpandedAccessInfo] = Field(default=None, alias="expandedAccessInfo")
    start_date_struct: Optional[PartialDateStruct] = Field(default=None, alias="startDateStruct")
    primary_completion_date_struct: Optional[PartialDateStruct] = Field(default=None, alias="primaryCompletionDateStruct")
    completion_date_struct: Optional[PartialDateStruct] = Field(default=None, alias="completionDateStruct")
    study_first_submit_date: Optional[date] = Field(default=None, alias="studyFirstSubmitDate")
    study_first_submit_qc_date: Optional[date] = Field(default=None, alias="studyFirstSubmitQcDate")
    study_first_post_date_struct: Optional[DateStruct] = Field(default=None, alias="studyFirstPostDateStruct")
    results_first_submit_date: Optional[date] = Field(default=None, alias="resultsFirstSubmitDate")
    results_first_submit_qc_date: Optional[date] = Field(default=None, alias="resultsFirstSubmitQcDate")
    results_first_post_date_struct: Optional[DateStruct] = Field(default=None, alias="resultsFirstPostDateStruct")
    disp_first_submit_date: Optional[date] = Field(default=None, alias="dispFirstSubmitDate")
    disp_first_submit_qc_date: Optional[date] = Field(default=None, alias="dispFirstSubmitQcDate")
    disp_first_post_date_struct: Optional[DateStruct] = Field(default=None, alias="dispFirstPostDateStruct")
    last_update_submit_date: Optional[date] = Field(default=None, alias="lastUpdateSubmitDate")
    last_update_post_date_struct: Optional[DateStruct] = Field(default=None, alias="lastUpdatePostDateStruct")
    __properties: ClassVar[List[str]] = ["statusVerifiedDate", "overallStatus", "lastKnownStatus", "delayedPosting", "whyStopped", "expandedAccessInfo", "startDateStruct", "primaryCompletionDateStruct", "completionDateStruct", "studyFirstSubmitDate", "studyFirstSubmitQcDate", "studyFirstPostDateStruct", "resultsFirstSubmitDate", "resultsFirstSubmitQcDate", "resultsFirstPostDateStruct", "dispFirstSubmitDate", "dispFirstSubmitQcDate", "dispFirstPostDateStruct", "lastUpdateSubmitDate", "lastUpdatePostDateStruct"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of expanded_access_info
        if self.expanded_access_info:
            _dict['expandedAccessInfo'] = self.expanded_access_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of start_date_struct
        if self.start_date_struct:
            _dict['startDateStruct'] = self.start_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of primary_completion_date_struct
        if self.primary_completion_date_struct:
            _dict['primaryCompletionDateStruct'] = self.primary_completion_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of completion_date_struct
        if self.completion_date_struct:
            _dict['completionDateStruct'] = self.completion_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of study_first_post_date_struct
        if self.study_first_post_date_struct:
            _dict['studyFirstPostDateStruct'] = self.study_first_post_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of results_first_post_date_struct
        if self.results_first_post_date_struct:
            _dict['resultsFirstPostDateStruct'] = self.results_first_post_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disp_first_post_date_struct
        if self.disp_first_post_date_struct:
            _dict['dispFirstPostDateStruct'] = self.disp_first_post_date_struct.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_update_post_date_struct
        if self.last_update_post_date_struct:
            _dict['lastUpdatePostDateStruct'] = self.last_update_post_date_struct.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "statusVerifiedDate": obj.get("statusVerifiedDate"),
            "overallStatus": obj.get("overallStatus"),
            "lastKnownStatus": obj.get("lastKnownStatus"),
            "delayedPosting": obj.get("delayedPosting"),
            "whyStopped": obj.get("whyStopped"),
            "expandedAccessInfo": ExpandedAccessInfo.from_dict(obj["expandedAccessInfo"]) if obj.get("expandedAccessInfo") is not None else None,
            "startDateStruct": PartialDateStruct.from_dict(obj["startDateStruct"]) if obj.get("startDateStruct") is not None else None,
            "primaryCompletionDateStruct": PartialDateStruct.from_dict(obj["primaryCompletionDateStruct"]) if obj.get("primaryCompletionDateStruct") is not None else None,
            "completionDateStruct": PartialDateStruct.from_dict(obj["completionDateStruct"]) if obj.get("completionDateStruct") is not None else None,
            "studyFirstSubmitDate": obj.get("studyFirstSubmitDate"),
            "studyFirstSubmitQcDate": obj.get("studyFirstSubmitQcDate"),
            "studyFirstPostDateStruct": DateStruct.from_dict(obj["studyFirstPostDateStruct"]) if obj.get("studyFirstPostDateStruct") is not None else None,
            "resultsFirstSubmitDate": obj.get("resultsFirstSubmitDate"),
            "resultsFirstSubmitQcDate": obj.get("resultsFirstSubmitQcDate"),
            "resultsFirstPostDateStruct": DateStruct.from_dict(obj["resultsFirstPostDateStruct"]) if obj.get("resultsFirstPostDateStruct") is not None else None,
            "dispFirstSubmitDate": obj.get("dispFirstSubmitDate"),
            "dispFirstSubmitQcDate": obj.get("dispFirstSubmitQcDate"),
            "dispFirstPostDateStruct": DateStruct.from_dict(obj["dispFirstPostDateStruct"]) if obj.get("dispFirstPostDateStruct") is not None else None,
            "lastUpdateSubmitDate": obj.get("lastUpdateSubmitDate"),
            "lastUpdatePostDateStruct": DateStruct.from_dict(obj["lastUpdatePostDateStruct"]) if obj.get("lastUpdatePostDateStruct") is not None else None
        })
        return _obj


