# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.first_mcp_info import FirstMcpInfo
from openapi_client.models.submission_info import SubmissionInfo
from typing import Optional, Set
from typing_extensions import Self

class SubmissionTracking(BaseModel):
    """
    SubmissionTracking
    """ # noqa: E501
    estimated_results_first_submit_date: Optional[date] = Field(default=None, alias="estimatedResultsFirstSubmitDate")
    first_mcp_info: Optional[FirstMcpInfo] = Field(default=None, alias="firstMcpInfo")
    submission_infos: Optional[List[SubmissionInfo]] = Field(default=None, alias="submissionInfos")
    __properties: ClassVar[List[str]] = ["estimatedResultsFirstSubmitDate", "firstMcpInfo", "submissionInfos"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubmissionTracking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of first_mcp_info
        if self.first_mcp_info:
            _dict['firstMcpInfo'] = self.first_mcp_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in submission_infos (list)
        _items = []
        if self.submission_infos:
            for _item_submission_infos in self.submission_infos:
                if _item_submission_infos:
                    _items.append(_item_submission_infos.to_dict())
            _dict['submissionInfos'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubmissionTracking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "estimatedResultsFirstSubmitDate": obj.get("estimatedResultsFirstSubmitDate"),
            "firstMcpInfo": FirstMcpInfo.from_dict(obj["firstMcpInfo"]) if obj.get("firstMcpInfo") is not None else None,
            "submissionInfos": [SubmissionInfo.from_dict(_item) for _item in obj["submissionInfos"]] if obj.get("submissionInfos") is not None else None
        })
        return _obj


