# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_document import SearchDocument

class TestSearchDocument(unittest.TestCase):
    """SearchDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchDocument:
        """Test SearchDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchDocument`
        """
        model = SearchDocument()
        if include_optional:
            return SearchDocument(
                areas = [
                    openapi_client.models.search_area.SearchArea(
                        name = '', 
                        param = '', 
                        parts = [
                            openapi_client.models.search_part.SearchPart(
                                is_enum = True, 
                                is_synonyms = True, 
                                pieces = [
                                    ''
                                    ], 
                                type = '', 
                                weight = 1.337, )
                            ], 
                        ui_label = '', )
                    ],
                name = ''
            )
        else:
            return SearchDocument(
                areas = [
                    openapi_client.models.search_area.SearchArea(
                        name = '', 
                        param = '', 
                        parts = [
                            openapi_client.models.search_part.SearchPart(
                                is_enum = True, 
                                is_synonyms = True, 
                                pieces = [
                                    ''
                                    ], 
                                type = '', 
                                weight = 1.337, )
                            ], 
                        ui_label = '', )
                    ],
                name = '',
        )
        """

    def testSearchDocument(self):
        """Test SearchDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
