# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.field_node import FieldNode

class TestFieldNode(unittest.TestCase):
    """FieldNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldNode:
        """Test FieldNode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldNode`
        """
        model = FieldNode()
        if include_optional:
            return FieldNode(
                alt_piece_names = [
                    ''
                    ],
                children = [
                    openapi_client.models.field_node.FieldNode(
                        alt_piece_names = [
                            ''
                            ], 
                        children = [
                            openapi_client.models.field_node.FieldNode(
                                ded_link = openapi_client.models.web_link.WebLink(
                                    label = '', 
                                    url = '', ), 
                                description = '', 
                                historic_only = True, 
                                indexed_only = True, 
                                is_enum = True, 
                                max_chars = 56, 
                                name = '', 
                                nested = True, 
                                piece = '', 
                                rules = '', 
                                source_type = '', 
                                synonyms = True, 
                                title = '', 
                                type = '', )
                            ], 
                        ded_link = openapi_client.models.web_link.WebLink(
                            label = '', 
                            url = '', ), 
                        description = '', 
                        historic_only = True, 
                        indexed_only = True, 
                        is_enum = True, 
                        max_chars = 56, 
                        name = '', 
                        nested = True, 
                        piece = '', 
                        rules = '', 
                        source_type = '', 
                        synonyms = True, 
                        title = '', 
                        type = '', )
                    ],
                ded_link = openapi_client.models.web_link.WebLink(
                    label = '', 
                    url = '', ),
                description = '',
                historic_only = True,
                indexed_only = True,
                is_enum = True,
                max_chars = 56,
                name = '',
                nested = True,
                piece = '',
                rules = '',
                source_type = '',
                synonyms = True,
                title = '',
                type = ''
            )
        else:
            return FieldNode(
                name = '',
                piece = '',
                source_type = '',
                type = '',
        )
        """

    def testFieldNode(self):
        """Test FieldNode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
