# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.arm_group_type import ArmGroupType

class TestArmGroupType(unittest.TestCase):
    """ArmGroupType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArmGroupType(self):
        """Test ArmGroupType"""
        # inst = ArmGroupType()

if __name__ == '__main__':
    unittest.main()
