# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outcomes_module import OutcomesModule

class TestOutcomesModule(unittest.TestCase):
    """OutcomesModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutcomesModule:
        """Test OutcomesModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutcomesModule`
        """
        model = OutcomesModule()
        if include_optional:
            return OutcomesModule(
                primary_outcomes = [
                    openapi_client.models.outcome.Outcome(
                        measure = '', 
                        description = '', 
                        time_frame = '', )
                    ],
                secondary_outcomes = [
                    openapi_client.models.outcome.Outcome(
                        measure = '', 
                        description = '', 
                        time_frame = '', )
                    ],
                other_outcomes = [
                    openapi_client.models.outcome.Outcome(
                        measure = '', 
                        description = '', 
                        time_frame = '', )
                    ]
            )
        else:
            return OutcomesModule(
        )
        """

    def testOutcomesModule(self):
        """Test OutcomesModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
