# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.adverse_events_module import AdverseEventsModule

class TestAdverseEventsModule(unittest.TestCase):
    """AdverseEventsModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdverseEventsModule:
        """Test AdverseEventsModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdverseEventsModule`
        """
        model = AdverseEventsModule()
        if include_optional:
            return AdverseEventsModule(
                frequency_threshold = '',
                time_frame = '',
                description = '',
                all_cause_mortality_comment = '',
                event_groups = [
                    openapi_client.models.event_group.EventGroup(
                        id = '', 
                        title = '', 
                        description = '', 
                        deaths_num_affected = 56, 
                        deaths_num_at_risk = 56, 
                        serious_num_affected = 56, 
                        serious_num_at_risk = 56, 
                        other_num_affected = 56, 
                        other_num_at_risk = 56, )
                    ],
                serious_events = [
                    openapi_client.models.adverse_event.AdverseEvent(
                        term = '', 
                        organ_system = '', 
                        source_vocabulary = '', 
                        assessment_type = 'NON_SYSTEMATIC_ASSESSMENT', 
                        notes = '', 
                        stats = [
                            openapi_client.models.event_stats.EventStats(
                                group_id = '', 
                                num_events = 56, 
                                num_affected = 56, 
                                num_at_risk = 56, )
                            ], )
                    ],
                other_events = [
                    openapi_client.models.adverse_event.AdverseEvent(
                        term = '', 
                        organ_system = '', 
                        source_vocabulary = '', 
                        assessment_type = 'NON_SYSTEMATIC_ASSESSMENT', 
                        notes = '', 
                        stats = [
                            openapi_client.models.event_stats.EventStats(
                                group_id = '', 
                                num_events = 56, 
                                num_affected = 56, 
                                num_at_risk = 56, )
                            ], )
                    ]
            )
        else:
            return AdverseEventsModule(
        )
        """

    def testAdverseEventsModule(self):
        """Test AdverseEventsModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
