# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.outcome_measure import OutcomeMeasure

class TestOutcomeMeasure(unittest.TestCase):
    """OutcomeMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutcomeMeasure:
        """Test OutcomeMeasure
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutcomeMeasure`
        """
        model = OutcomeMeasure()
        if include_optional:
            return OutcomeMeasure(
                type = 'PRIMARY',
                title = '',
                description = '',
                population_description = '',
                reporting_status = 'NOT_POSTED',
                anticipated_posting_date = '',
                param_type = 'GEOMETRIC_MEAN',
                dispersion_type = '',
                unit_of_measure = '',
                calculate_pct = True,
                time_frame = '',
                type_units_analyzed = '',
                denom_units_selected = '',
                groups = [
                    openapi_client.models.measure_group.MeasureGroup(
                        id = '', 
                        title = '', 
                        description = '', )
                    ],
                denoms = [
                    openapi_client.models.denom.Denom(
                        units = '', 
                        counts = [
                            openapi_client.models.denom_count.DenomCount(
                                group_id = '', 
                                value = '', )
                            ], )
                    ],
                classes = [
                    openapi_client.models.measure_class.MeasureClass(
                        title = '', 
                        denoms = [
                            openapi_client.models.denom.Denom(
                                units = '', 
                                counts = [
                                    openapi_client.models.denom_count.DenomCount(
                                        group_id = '', 
                                        value = '', )
                                    ], )
                            ], 
                        categories = [
                            openapi_client.models.measure_category.MeasureCategory(
                                title = '', 
                                measurements = [
                                    openapi_client.models.measurement.Measurement(
                                        group_id = '', 
                                        value = '', 
                                        spread = '', 
                                        lower_limit = '', 
                                        upper_limit = '', 
                                        comment = '', )
                                    ], )
                            ], )
                    ],
                analyses = [
                    openapi_client.models.measure_analysis.MeasureAnalysis(
                        param_type = '', 
                        param_value = '', 
                        dispersion_type = 'STANDARD_DEVIATION', 
                        dispersion_value = '', 
                        statistical_method = '', 
                        statistical_comment = '', 
                        p_value = '', 
                        p_value_comment = '', 
                        ci_num_sides = 'ONE_SIDED', 
                        ci_pct_value = '', 
                        ci_lower_limit = '', 
                        ci_upper_limit = '', 
                        ci_lower_limit_comment = '', 
                        ci_upper_limit_comment = '', 
                        estimate_comment = '', 
                        tested_non_inferiority = True, 
                        non_inferiority_type = 'SUPERIORITY', 
                        non_inferiority_comment = '', 
                        other_analysis_description = '', 
                        group_description = '', 
                        group_ids = [
                            ''
                            ], )
                    ]
            )
        else:
            return OutcomeMeasure(
        )
        """

    def testOutcomeMeasure(self):
        """Test OutcomeMeasure"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
