# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agreement_restriction_type import AgreementRestrictionType

class TestAgreementRestrictionType(unittest.TestCase):
    """AgreementRestrictionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgreementRestrictionType(self):
        """Test AgreementRestrictionType"""
        # inst = AgreementRestrictionType()

if __name__ == '__main__':
    unittest.main()
