# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.string_stats import StringStats

class TestStringStats(unittest.TestCase):
    """StringStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringStats:
        """Test StringStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringStats`
        """
        model = StringStats()
        if include_optional:
            return StringStats(
                var_field = '',
                longest = openapi_client.models.longest_string.LongestString(
                    length = 56, 
                    nct_id = '', 
                    value = '', ),
                missing_studies_count = 56,
                piece = '',
                top_values = [
                    openapi_client.models.value_count.ValueCount(
                        studies_count = 56, 
                        value = '', )
                    ],
                type = 'ENUM',
                unique_values_count = 56
            )
        else:
            return StringStats(
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                type = 'ENUM',
                unique_values_count = 56,
        )
        """

    def testStringStats(self):
        """Test StringStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
