# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.more_info_module import MoreInfoModule

class TestMoreInfoModule(unittest.TestCase):
    """MoreInfoModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MoreInfoModule:
        """Test MoreInfoModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MoreInfoModule`
        """
        model = MoreInfoModule()
        if include_optional:
            return MoreInfoModule(
                limitations_and_caveats = openapi_client.models.limitations_and_caveats.LimitationsAndCaveats(
                    description = '', ),
                certain_agreement = openapi_client.models.certain_agreement.CertainAgreement(
                    pi_sponsor_employee = True, 
                    restriction_type = 'LTE60', 
                    restrictive_agreement = True, 
                    other_details = '', ),
                point_of_contact = openapi_client.models.point_of_contact.PointOfContact(
                    title = '', 
                    organization = '', 
                    email = '', 
                    phone = '', 
                    phone_ext = '', )
            )
        else:
            return MoreInfoModule(
        )
        """

    def testMoreInfoModule(self):
        """Test MoreInfoModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
