# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.expanded_access_info import ExpandedAccessInfo

class TestExpandedAccessInfo(unittest.TestCase):
    """ExpandedAccessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExpandedAccessInfo:
        """Test ExpandedAccessInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExpandedAccessInfo`
        """
        model = ExpandedAccessInfo()
        if include_optional:
            return ExpandedAccessInfo(
                has_expanded_access = True,
                nct_id = '',
                status_for_nct_id = 'AVAILABLE'
            )
        else:
            return ExpandedAccessInfo(
        )
        """

    def testExpandedAccessInfo(self):
        """Test ExpandedAccessInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
