# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_sizes import ListSizes

class TestListSizes(unittest.TestCase):
    """ListSizes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSizes:
        """Test ListSizes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSizes`
        """
        model = ListSizes()
        if include_optional:
            return ListSizes(
                var_field = '',
                max_size = 56,
                min_size = 56,
                piece = '',
                top_sizes = [
                    openapi_client.models.list_size.ListSize(
                        size = 56, 
                        studies_count = 56, )
                    ],
                unique_sizes_count = 56
            )
        else:
            return ListSizes(
                var_field = '',
                piece = '',
                unique_sizes_count = 56,
        )
        """

    def testListSizes(self):
        """Test ListSizes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
