# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.integer_stats import IntegerStats

class TestIntegerStats(unittest.TestCase):
    """IntegerStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegerStats:
        """Test IntegerStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegerStats`
        """
        model = IntegerStats()
        if include_optional:
            return IntegerStats(
                avg = 1.337,
                var_field = '',
                max = 56,
                min = 56,
                missing_studies_count = 56,
                piece = '',
                type = 'ENUM'
            )
        else:
            return IntegerStats(
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                type = 'ENUM',
        )
        """

    def testIntegerStats(self):
        """Test IntegerStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
