# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.adverse_event import AdverseEvent
from openapi_client.models.event_group import EventGroup
from typing import Optional, Set
from typing_extensions import Self

class AdverseEventsModule(BaseModel):
    """
    AdverseEventsModule
    """ # noqa: E501
    frequency_threshold: Optional[StrictStr] = Field(default=None, alias="frequencyThreshold")
    time_frame: Optional[StrictStr] = Field(default=None, alias="timeFrame")
    description: Optional[StrictStr] = None
    all_cause_mortality_comment: Optional[StrictStr] = Field(default=None, alias="allCauseMortalityComment")
    event_groups: Optional[List[EventGroup]] = Field(default=None, alias="eventGroups")
    serious_events: Optional[List[AdverseEvent]] = Field(default=None, alias="seriousEvents")
    other_events: Optional[List[AdverseEvent]] = Field(default=None, alias="otherEvents")
    __properties: ClassVar[List[str]] = ["frequencyThreshold", "timeFrame", "description", "allCauseMortalityComment", "eventGroups", "seriousEvents", "otherEvents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdverseEventsModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in event_groups (list)
        _items = []
        if self.event_groups:
            for _item_event_groups in self.event_groups:
                if _item_event_groups:
                    _items.append(_item_event_groups.to_dict())
            _dict['eventGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in serious_events (list)
        _items = []
        if self.serious_events:
            for _item_serious_events in self.serious_events:
                if _item_serious_events:
                    _items.append(_item_serious_events.to_dict())
            _dict['seriousEvents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in other_events (list)
        _items = []
        if self.other_events:
            for _item_other_events in self.other_events:
                if _item_other_events:
                    _items.append(_item_other_events.to_dict())
            _dict['otherEvents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdverseEventsModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "frequencyThreshold": obj.get("frequencyThreshold"),
            "timeFrame": obj.get("timeFrame"),
            "description": obj.get("description"),
            "allCauseMortalityComment": obj.get("allCauseMortalityComment"),
            "eventGroups": [EventGroup.from_dict(_item) for _item in obj["eventGroups"]] if obj.get("eventGroups") is not None else None,
            "seriousEvents": [AdverseEvent.from_dict(_item) for _item in obj["seriousEvents"]] if obj.get("seriousEvents") is not None else None,
            "otherEvents": [AdverseEvent.from_dict(_item) for _item in obj["otherEvents"]] if obj.get("otherEvents") is not None else None
        })
        return _obj


