# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.baseline_measure import BaselineMeasure
from openapi_client.models.denom import Denom
from openapi_client.models.measure_group import MeasureGroup
from typing import Optional, Set
from typing_extensions import Self

class BaselineCharacteristicsModule(BaseModel):
    """
    BaselineCharacteristicsModule
    """ # noqa: E501
    population_description: Optional[StrictStr] = Field(default=None, alias="populationDescription")
    type_units_analyzed: Optional[StrictStr] = Field(default=None, alias="typeUnitsAnalyzed")
    groups: Optional[List[MeasureGroup]] = None
    denoms: Optional[List[Denom]] = None
    measures: Optional[List[BaselineMeasure]] = None
    __properties: ClassVar[List[str]] = ["populationDescription", "typeUnitsAnalyzed", "groups", "denoms", "measures"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaselineCharacteristicsModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in denoms (list)
        _items = []
        if self.denoms:
            for _item_denoms in self.denoms:
                if _item_denoms:
                    _items.append(_item_denoms.to_dict())
            _dict['denoms'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in measures (list)
        _items = []
        if self.measures:
            for _item_measures in self.measures:
                if _item_measures:
                    _items.append(_item_measures.to_dict())
            _dict['measures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaselineCharacteristicsModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "populationDescription": obj.get("populationDescription"),
            "typeUnitsAnalyzed": obj.get("typeUnitsAnalyzed"),
            "groups": [MeasureGroup.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "denoms": [Denom.from_dict(_item) for _item in obj["denoms"]] if obj.get("denoms") is not None else None,
            "measures": [BaselineMeasure.from_dict(_item) for _item in obj["measures"]] if obj.get("measures") is not None else None
        })
        return _obj


