# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.browse_branch import BrowseBranch
from openapi_client.models.browse_leaf import BrowseLeaf
from openapi_client.models.mesh import Mesh
from typing import Optional, Set
from typing_extensions import Self

class BrowseModule(BaseModel):
    """
    BrowseModule
    """ # noqa: E501
    meshes: Optional[List[Mesh]] = None
    ancestors: Optional[List[Mesh]] = None
    browse_leaves: Optional[List[BrowseLeaf]] = Field(default=None, alias="browseLeaves")
    browse_branches: Optional[List[BrowseBranch]] = Field(default=None, alias="browseBranches")
    __properties: ClassVar[List[str]] = ["meshes", "ancestors", "browseLeaves", "browseBranches"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrowseModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in meshes (list)
        _items = []
        if self.meshes:
            for _item_meshes in self.meshes:
                if _item_meshes:
                    _items.append(_item_meshes.to_dict())
            _dict['meshes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ancestors (list)
        _items = []
        if self.ancestors:
            for _item_ancestors in self.ancestors:
                if _item_ancestors:
                    _items.append(_item_ancestors.to_dict())
            _dict['ancestors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in browse_leaves (list)
        _items = []
        if self.browse_leaves:
            for _item_browse_leaves in self.browse_leaves:
                if _item_browse_leaves:
                    _items.append(_item_browse_leaves.to_dict())
            _dict['browseLeaves'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in browse_branches (list)
        _items = []
        if self.browse_branches:
            for _item_browse_branches in self.browse_branches:
                if _item_browse_branches:
                    _items.append(_item_browse_branches.to_dict())
            _dict['browseBranches'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrowseModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meshes": [Mesh.from_dict(_item) for _item in obj["meshes"]] if obj.get("meshes") is not None else None,
            "ancestors": [Mesh.from_dict(_item) for _item in obj["ancestors"]] if obj.get("ancestors") is not None else None,
            "browseLeaves": [BrowseLeaf.from_dict(_item) for _item in obj["browseLeaves"]] if obj.get("browseLeaves") is not None else None,
            "browseBranches": [BrowseBranch.from_dict(_item) for _item in obj["browseBranches"]] if obj.get("browseBranches") is not None else None
        })
        return _obj


