# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.drop_withdraw import DropWithdraw
from openapi_client.models.flow_milestone import FlowMilestone
from typing import Optional, Set
from typing_extensions import Self

class FlowPeriod(BaseModel):
    """
    FlowPeriod
    """ # noqa: E501
    title: Optional[StrictStr] = None
    milestones: Optional[List[FlowMilestone]] = None
    drop_withdraws: Optional[List[DropWithdraw]] = Field(default=None, alias="dropWithdraws")
    __properties: ClassVar[List[str]] = ["title", "milestones", "dropWithdraws"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlowPeriod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in milestones (list)
        _items = []
        if self.milestones:
            for _item_milestones in self.milestones:
                if _item_milestones:
                    _items.append(_item_milestones.to_dict())
            _dict['milestones'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in drop_withdraws (list)
        _items = []
        if self.drop_withdraws:
            for _item_drop_withdraws in self.drop_withdraws:
                if _item_drop_withdraws:
                    _items.append(_item_drop_withdraws.to_dict())
            _dict['dropWithdraws'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlowPeriod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "milestones": [FlowMilestone.from_dict(_item) for _item in obj["milestones"]] if obj.get("milestones") is not None else None,
            "dropWithdraws": [DropWithdraw.from_dict(_item) for _item in obj["dropWithdraws"]] if obj.get("dropWithdraws") is not None else None
        })
        return _obj


