# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.org_study_id_info import OrgStudyIdInfo
from openapi_client.models.organization import Organization
from openapi_client.models.secondary_id_info import SecondaryIdInfo
from typing import Optional, Set
from typing_extensions import Self

class IdentificationModule(BaseModel):
    """
    IdentificationModule
    """ # noqa: E501
    nct_id: Optional[StrictStr] = Field(default=None, alias="nctId")
    nct_id_aliases: Optional[List[StrictStr]] = Field(default=None, alias="nctIdAliases")
    org_study_id_info: Optional[OrgStudyIdInfo] = Field(default=None, alias="orgStudyIdInfo")
    secondary_id_infos: Optional[List[SecondaryIdInfo]] = Field(default=None, alias="secondaryIdInfos")
    brief_title: Optional[StrictStr] = Field(default=None, alias="briefTitle")
    official_title: Optional[StrictStr] = Field(default=None, alias="officialTitle")
    acronym: Optional[StrictStr] = None
    organization: Optional[Organization] = None
    __properties: ClassVar[List[str]] = ["nctId", "nctIdAliases", "orgStudyIdInfo", "secondaryIdInfos", "briefTitle", "officialTitle", "acronym", "organization"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentificationModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of org_study_id_info
        if self.org_study_id_info:
            _dict['orgStudyIdInfo'] = self.org_study_id_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in secondary_id_infos (list)
        _items = []
        if self.secondary_id_infos:
            for _item_secondary_id_infos in self.secondary_id_infos:
                if _item_secondary_id_infos:
                    _items.append(_item_secondary_id_infos.to_dict())
            _dict['secondaryIdInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of organization
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentificationModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nctId": obj.get("nctId"),
            "nctIdAliases": obj.get("nctIdAliases"),
            "orgStudyIdInfo": OrgStudyIdInfo.from_dict(obj["orgStudyIdInfo"]) if obj.get("orgStudyIdInfo") is not None else None,
            "secondaryIdInfos": [SecondaryIdInfo.from_dict(_item) for _item in obj["secondaryIdInfos"]] if obj.get("secondaryIdInfos") is not None else None,
            "briefTitle": obj.get("briefTitle"),
            "officialTitle": obj.get("officialTitle"),
            "acronym": obj.get("acronym"),
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None
        })
        return _obj


