# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.analysis_dispersion_type import AnalysisDispersionType
from openapi_client.models.confidence_interval_num_sides import ConfidenceIntervalNumSides
from openapi_client.models.non_inferiority_type import NonInferiorityType
from typing import Optional, Set
from typing_extensions import Self

class MeasureAnalysis(BaseModel):
    """
    MeasureAnalysis
    """ # noqa: E501
    param_type: Optional[StrictStr] = Field(default=None, alias="paramType")
    param_value: Optional[StrictStr] = Field(default=None, alias="paramValue")
    dispersion_type: Optional[AnalysisDispersionType] = Field(default=None, alias="dispersionType")
    dispersion_value: Optional[StrictStr] = Field(default=None, alias="dispersionValue")
    statistical_method: Optional[StrictStr] = Field(default=None, alias="statisticalMethod")
    statistical_comment: Optional[StrictStr] = Field(default=None, alias="statisticalComment")
    p_value: Optional[StrictStr] = Field(default=None, alias="pValue")
    p_value_comment: Optional[StrictStr] = Field(default=None, alias="pValueComment")
    ci_num_sides: Optional[ConfidenceIntervalNumSides] = Field(default=None, alias="ciNumSides")
    ci_pct_value: Optional[StrictStr] = Field(default=None, alias="ciPctValue")
    ci_lower_limit: Optional[StrictStr] = Field(default=None, alias="ciLowerLimit")
    ci_upper_limit: Optional[StrictStr] = Field(default=None, alias="ciUpperLimit")
    ci_lower_limit_comment: Optional[StrictStr] = Field(default=None, alias="ciLowerLimitComment")
    ci_upper_limit_comment: Optional[StrictStr] = Field(default=None, alias="ciUpperLimitComment")
    estimate_comment: Optional[StrictStr] = Field(default=None, alias="estimateComment")
    tested_non_inferiority: Optional[StrictBool] = Field(default=None, alias="testedNonInferiority")
    non_inferiority_type: Optional[NonInferiorityType] = Field(default=None, alias="nonInferiorityType")
    non_inferiority_comment: Optional[StrictStr] = Field(default=None, alias="nonInferiorityComment")
    other_analysis_description: Optional[StrictStr] = Field(default=None, alias="otherAnalysisDescription")
    group_description: Optional[StrictStr] = Field(default=None, alias="groupDescription")
    group_ids: Optional[List[StrictStr]] = Field(default=None, alias="groupIds")
    __properties: ClassVar[List[str]] = ["paramType", "paramValue", "dispersionType", "dispersionValue", "statisticalMethod", "statisticalComment", "pValue", "pValueComment", "ciNumSides", "ciPctValue", "ciLowerLimit", "ciUpperLimit", "ciLowerLimitComment", "ciUpperLimitComment", "estimateComment", "testedNonInferiority", "nonInferiorityType", "nonInferiorityComment", "otherAnalysisDescription", "groupDescription", "groupIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasureAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasureAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paramType": obj.get("paramType"),
            "paramValue": obj.get("paramValue"),
            "dispersionType": obj.get("dispersionType"),
            "dispersionValue": obj.get("dispersionValue"),
            "statisticalMethod": obj.get("statisticalMethod"),
            "statisticalComment": obj.get("statisticalComment"),
            "pValue": obj.get("pValue"),
            "pValueComment": obj.get("pValueComment"),
            "ciNumSides": obj.get("ciNumSides"),
            "ciPctValue": obj.get("ciPctValue"),
            "ciLowerLimit": obj.get("ciLowerLimit"),
            "ciUpperLimit": obj.get("ciUpperLimit"),
            "ciLowerLimitComment": obj.get("ciLowerLimitComment"),
            "ciUpperLimitComment": obj.get("ciUpperLimitComment"),
            "estimateComment": obj.get("estimateComment"),
            "testedNonInferiority": obj.get("testedNonInferiority"),
            "nonInferiorityType": obj.get("nonInferiorityType"),
            "nonInferiorityComment": obj.get("nonInferiorityComment"),
            "otherAnalysisDescription": obj.get("otherAnalysisDescription"),
            "groupDescription": obj.get("groupDescription"),
            "groupIds": obj.get("groupIds")
        })
        return _obj


