# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.outcome import Outcome
from typing import Optional, Set
from typing_extensions import Self

class OutcomesModule(BaseModel):
    """
    OutcomesModule
    """ # noqa: E501
    primary_outcomes: Optional[List[Outcome]] = Field(default=None, alias="primaryOutcomes")
    secondary_outcomes: Optional[List[Outcome]] = Field(default=None, alias="secondaryOutcomes")
    other_outcomes: Optional[List[Outcome]] = Field(default=None, alias="otherOutcomes")
    __properties: ClassVar[List[str]] = ["primaryOutcomes", "secondaryOutcomes", "otherOutcomes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutcomesModule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in primary_outcomes (list)
        _items = []
        if self.primary_outcomes:
            for _item_primary_outcomes in self.primary_outcomes:
                if _item_primary_outcomes:
                    _items.append(_item_primary_outcomes.to_dict())
            _dict['primaryOutcomes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in secondary_outcomes (list)
        _items = []
        if self.secondary_outcomes:
            for _item_secondary_outcomes in self.secondary_outcomes:
                if _item_secondary_outcomes:
                    _items.append(_item_secondary_outcomes.to_dict())
            _dict['secondaryOutcomes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in other_outcomes (list)
        _items = []
        if self.other_outcomes:
            for _item_other_outcomes in self.other_outcomes:
                if _item_other_outcomes:
                    _items.append(_item_other_outcomes.to_dict())
            _dict['otherOutcomes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutcomesModule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primaryOutcomes": [Outcome.from_dict(_item) for _item in obj["primaryOutcomes"]] if obj.get("primaryOutcomes") is not None else None,
            "secondaryOutcomes": [Outcome.from_dict(_item) for _item in obj["secondaryOutcomes"]] if obj.get("secondaryOutcomes") is not None else None,
            "otherOutcomes": [Outcome.from_dict(_item) for _item in obj["otherOutcomes"]] if obj.get("otherOutcomes") is not None else None
        })
        return _obj


