# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.responsible_party_type import ResponsiblePartyType
from typing import Optional, Set
from typing_extensions import Self

class ResponsibleParty(BaseModel):
    """
    ResponsibleParty
    """ # noqa: E501
    type: Optional[ResponsiblePartyType] = None
    investigator_full_name: Optional[StrictStr] = Field(default=None, alias="investigatorFullName")
    investigator_title: Optional[StrictStr] = Field(default=None, alias="investigatorTitle")
    investigator_affiliation: Optional[StrictStr] = Field(default=None, alias="investigatorAffiliation")
    old_name_title: Optional[StrictStr] = Field(default=None, alias="oldNameTitle")
    old_organization: Optional[StrictStr] = Field(default=None, alias="oldOrganization")
    __properties: ClassVar[List[str]] = ["type", "investigatorFullName", "investigatorTitle", "investigatorAffiliation", "oldNameTitle", "oldOrganization"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponsibleParty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponsibleParty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "investigatorFullName": obj.get("investigatorFullName"),
            "investigatorTitle": obj.get("investigatorTitle"),
            "investigatorAffiliation": obj.get("investigatorAffiliation"),
            "oldNameTitle": obj.get("oldNameTitle"),
            "oldOrganization": obj.get("oldOrganization")
        })
        return _obj


