# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.annotation_section import AnnotationSection
from openapi_client.models.derived_section import DerivedSection
from openapi_client.models.document_section import DocumentSection
from openapi_client.models.protocol_section import ProtocolSection
from openapi_client.models.results_section import ResultsSection
from typing import Optional, Set
from typing_extensions import Self

class Study(BaseModel):
    """
    Study
    """ # noqa: E501
    protocol_section: Optional[ProtocolSection] = Field(default=None, alias="protocolSection")
    results_section: Optional[ResultsSection] = Field(default=None, alias="resultsSection")
    annotation_section: Optional[AnnotationSection] = Field(default=None, alias="annotationSection")
    document_section: Optional[DocumentSection] = Field(default=None, alias="documentSection")
    derived_section: Optional[DerivedSection] = Field(default=None, alias="derivedSection")
    has_results: Optional[StrictBool] = Field(default=None, alias="hasResults")
    __properties: ClassVar[List[str]] = ["protocolSection", "resultsSection", "annotationSection", "documentSection", "derivedSection", "hasResults"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Study from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of protocol_section
        if self.protocol_section:
            _dict['protocolSection'] = self.protocol_section.to_dict()
        # override the default output from pydantic by calling `to_dict()` of results_section
        if self.results_section:
            _dict['resultsSection'] = self.results_section.to_dict()
        # override the default output from pydantic by calling `to_dict()` of annotation_section
        if self.annotation_section:
            _dict['annotationSection'] = self.annotation_section.to_dict()
        # override the default output from pydantic by calling `to_dict()` of document_section
        if self.document_section:
            _dict['documentSection'] = self.document_section.to_dict()
        # override the default output from pydantic by calling `to_dict()` of derived_section
        if self.derived_section:
            _dict['derivedSection'] = self.derived_section.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Study from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "protocolSection": ProtocolSection.from_dict(obj["protocolSection"]) if obj.get("protocolSection") is not None else None,
            "resultsSection": ResultsSection.from_dict(obj["resultsSection"]) if obj.get("resultsSection") is not None else None,
            "annotationSection": AnnotationSection.from_dict(obj["annotationSection"]) if obj.get("annotationSection") is not None else None,
            "documentSection": DocumentSection.from_dict(obj["documentSection"]) if obj.get("documentSection") is not None else None,
            "derivedSection": DerivedSection.from_dict(obj["derivedSection"]) if obj.get("derivedSection") is not None else None,
            "hasResults": obj.get("hasResults")
        })
        return _obj


