# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.design_info import DesignInfo

class TestDesignInfo(unittest.TestCase):
    """DesignInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DesignInfo:
        """Test DesignInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DesignInfo`
        """
        model = DesignInfo()
        if include_optional:
            return DesignInfo(
                allocation = 'RANDOMIZED',
                intervention_model = 'SINGLE_GROUP',
                intervention_model_description = '',
                primary_purpose = 'TREATMENT',
                observational_model = 'COHORT',
                time_perspective = 'RETROSPECTIVE',
                masking_info = openapi_client.models.masking_block.MaskingBlock(
                    masking = 'NONE', 
                    masking_description = '', 
                    who_masked = [
                        'PARTICIPANT'
                        ], )
            )
        else:
            return DesignInfo(
        )
        """

    def testDesignInfo(self):
        """Test DesignInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
