# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_section import DocumentSection

class TestDocumentSection(unittest.TestCase):
    """DocumentSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentSection:
        """Test DocumentSection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentSection`
        """
        model = DocumentSection()
        if include_optional:
            return DocumentSection(
                large_document_module = openapi_client.models.large_document_module.LargeDocumentModule(
                    no_sap = True, 
                    large_docs = [
                        openapi_client.models.large_doc.LargeDoc(
                            type_abbrev = '', 
                            has_protocol = True, 
                            has_sap = True, 
                            has_icf = True, 
                            label = '', 
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            upload_date = '', 
                            filename = '', 
                            size = 56, )
                        ], )
            )
        else:
            return DocumentSection(
        )
        """

    def testDocumentSection(self):
        """Test DocumentSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
