# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.location import Location

class TestLocation(unittest.TestCase):
    """Location unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Location:
        """Test Location
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Location`
        """
        model = Location()
        if include_optional:
            return Location(
                facility = '',
                status = 'ACTIVE_NOT_RECRUITING',
                city = '',
                state = '',
                zip = '',
                country = '',
                contacts = [
                    openapi_client.models.contact.Contact(
                        name = '', 
                        role = 'STUDY_CHAIR', 
                        phone = '', 
                        phone_ext = '', 
                        email = '', )
                    ],
                country_code = '',
                geo_point = openapi_client.models.geo_point.GeoPoint(
                    lat = 1.337, 
                    lon = 1.337, )
            )
        else:
            return Location(
        )
        """

    def testLocation(self):
        """Test Location"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
