# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.participant_flow_module import ParticipantFlowModule

class TestParticipantFlowModule(unittest.TestCase):
    """ParticipantFlowModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParticipantFlowModule:
        """Test ParticipantFlowModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParticipantFlowModule`
        """
        model = ParticipantFlowModule()
        if include_optional:
            return ParticipantFlowModule(
                pre_assignment_details = '',
                recruitment_details = '',
                type_units_analyzed = '',
                groups = [
                    openapi_client.models.flow_group.FlowGroup(
                        id = '', 
                        title = '', 
                        description = '', )
                    ],
                periods = [
                    openapi_client.models.flow_period.FlowPeriod(
                        title = '', 
                        milestones = [
                            openapi_client.models.flow_milestone.FlowMilestone(
                                type = '', 
                                comment = '', 
                                achievements = [
                                    openapi_client.models.flow_stats.FlowStats(
                                        group_id = '', 
                                        comment = '', 
                                        num_subjects = '', 
                                        num_units = '', )
                                    ], )
                            ], 
                        drop_withdraws = [
                            openapi_client.models.drop_withdraw.DropWithdraw(
                                type = '', 
                                comment = '', 
                                reasons = [
                                    openapi_client.models.flow_stats.FlowStats(
                                        group_id = '', 
                                        comment = '', 
                                        num_subjects = '', 
                                        num_units = '', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return ParticipantFlowModule(
        )
        """

    def testParticipantFlowModule(self):
        """Test ParticipantFlowModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
