# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boolean_stats import BooleanStats

class TestBooleanStats(unittest.TestCase):
    """BooleanStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BooleanStats:
        """Test BooleanStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BooleanStats`
        """
        model = BooleanStats()
        if include_optional:
            return BooleanStats(
                false_count = 56,
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                true_count = 56,
                type = 'ENUM'
            )
        else:
            return BooleanStats(
                false_count = 56,
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                true_count = 56,
                type = 'ENUM',
        )
        """

    def testBooleanStats(self):
        """Test BooleanStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
