# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.oversight_module import OversightModule

class TestOversightModule(unittest.TestCase):
    """OversightModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OversightModule:
        """Test OversightModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OversightModule`
        """
        model = OversightModule()
        if include_optional:
            return OversightModule(
                oversight_has_dmc = True,
                is_fda_regulated_drug = True,
                is_fda_regulated_device = True,
                is_unapproved_device = True,
                is_ppsd = True,
                is_us_export = True,
                fdaaa801_violation = True
            )
        else:
            return OversightModule(
        )
        """

    def testOversightModule(self):
        """Test OversightModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
