# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.status_module import StatusModule

class TestStatusModule(unittest.TestCase):
    """StatusModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusModule:
        """Test StatusModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusModule`
        """
        model = StatusModule()
        if include_optional:
            return StatusModule(
                status_verified_date = '',
                overall_status = 'ACTIVE_NOT_RECRUITING',
                last_known_status = 'ACTIVE_NOT_RECRUITING',
                delayed_posting = True,
                why_stopped = '',
                expanded_access_info = openapi_client.models.expanded_access_info.ExpandedAccessInfo(
                    has_expanded_access = True, 
                    nct_id = '', 
                    status_for_nct_id = 'AVAILABLE', ),
                start_date_struct = openapi_client.models.partial_date_struct.PartialDateStruct(
                    date = '', 
                    type = 'ACTUAL', ),
                primary_completion_date_struct = openapi_client.models.partial_date_struct.PartialDateStruct(
                    date = '', 
                    type = 'ACTUAL', ),
                completion_date_struct = openapi_client.models.partial_date_struct.PartialDateStruct(
                    date = '', 
                    type = 'ACTUAL', ),
                study_first_submit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                study_first_submit_qc_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                study_first_post_date_struct = openapi_client.models.date_struct.DateStruct(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    type = 'ACTUAL', ),
                results_first_submit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                results_first_submit_qc_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                results_first_post_date_struct = openapi_client.models.date_struct.DateStruct(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    type = 'ACTUAL', ),
                disp_first_submit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                disp_first_submit_qc_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                disp_first_post_date_struct = openapi_client.models.date_struct.DateStruct(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    type = 'ACTUAL', ),
                last_update_submit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                last_update_post_date_struct = openapi_client.models.date_struct.DateStruct(
                    date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    type = 'ACTUAL', )
            )
        else:
            return StatusModule(
        )
        """

    def testStatusModule(self):
        """Test StatusModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
