# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.field_values_stats import FieldValuesStats

class TestFieldValuesStats(unittest.TestCase):
    """FieldValuesStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldValuesStats:
        """Test FieldValuesStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldValuesStats`
        """
        model = FieldValuesStats()
        if include_optional:
            return FieldValuesStats(
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                top_values = [
                    openapi_client.models.value_count.ValueCount(
                        studies_count = 56, 
                        value = '', )
                    ],
                type = 'ENUM',
                unique_values_count = 56,
                longest = openapi_client.models.longest_string.LongestString(
                    length = 56, 
                    nct_id = '', 
                    value = '', ),
                formats = [
                    ''
                    ],
                max = 1.337,
                min = 1.337,
                avg = 1.337,
                false_count = 56,
                true_count = 56
            )
        else:
            return FieldValuesStats(
                var_field = '',
                missing_studies_count = 56,
                piece = '',
                type = 'ENUM',
                unique_values_count = 56,
                formats = [
                    ''
                    ],
                false_count = 56,
                true_count = 56,
        )
        """

    def testFieldValuesStats(self):
        """Test FieldValuesStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
