# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.annotation_module import AnnotationModule

class TestAnnotationModule(unittest.TestCase):
    """AnnotationModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationModule:
        """Test AnnotationModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationModule`
        """
        model = AnnotationModule()
        if include_optional:
            return AnnotationModule(
                unposted_annotation = openapi_client.models.unposted_annotation.UnpostedAnnotation(
                    unposted_responsible_party = '', 
                    unposted_events = [
                        openapi_client.models.unposted_event.UnpostedEvent(
                            type = 'RESET', 
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            date_unknown = True, )
                        ], ),
                violation_annotation = openapi_client.models.violation_annotation.ViolationAnnotation(
                    violation_events = [
                        openapi_client.models.violation_event.ViolationEvent(
                            type = 'VIOLATION_IDENTIFIED', 
                            description = '', 
                            creation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            issued_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            release_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            posted_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                        ], )
            )
        else:
            return AnnotationModule(
        )
        """

    def testAnnotationModule(self):
        """Test AnnotationModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
