# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gzip_stats import GzipStats

class TestGzipStats(unittest.TestCase):
    """GzipStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GzipStats:
        """Test GzipStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GzipStats`
        """
        model = GzipStats()
        if include_optional:
            return GzipStats(
                average_size_bytes = 56,
                largest_studies = [
                    openapi_client.models.study_size.StudySize(
                        id = '', 
                        size_bytes = 56, )
                    ],
                percentiles = None,
                ranges = [
                    openapi_client.models.dist_item.DistItem(
                        size_range = '', 
                        studies_count = 56, )
                    ],
                total_studies = 56
            )
        else:
            return GzipStats(
                average_size_bytes = 56,
                largest_studies = [
                    openapi_client.models.study_size.StudySize(
                        id = '', 
                        size_bytes = 56, )
                    ],
                percentiles = None,
                ranges = [
                    openapi_client.models.dist_item.DistItem(
                        size_range = '', 
                        studies_count = 56, )
                    ],
                total_studies = 56,
        )
        """

    def testGzipStats(self):
        """Test GzipStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
