# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.identification_module import IdentificationModule

class TestIdentificationModule(unittest.TestCase):
    """IdentificationModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentificationModule:
        """Test IdentificationModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentificationModule`
        """
        model = IdentificationModule()
        if include_optional:
            return IdentificationModule(
                nct_id = '',
                nct_id_aliases = [
                    ''
                    ],
                org_study_id_info = openapi_client.models.org_study_id_info.OrgStudyIdInfo(
                    id = '', 
                    type = 'NIH', 
                    link = '', ),
                secondary_id_infos = [
                    openapi_client.models.secondary_id_info.SecondaryIdInfo(
                        id = '', 
                        type = 'NIH', 
                        domain = '', 
                        link = '', )
                    ],
                brief_title = '',
                official_title = '',
                acronym = '',
                organization = openapi_client.models.organization.Organization(
                    full_name = '', 
                    class = 'NIH', )
            )
        else:
            return IdentificationModule(
        )
        """

    def testIdentificationModule(self):
        """Test IdentificationModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
