# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.eligibility_module import EligibilityModule

class TestEligibilityModule(unittest.TestCase):
    """EligibilityModule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EligibilityModule:
        """Test EligibilityModule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EligibilityModule`
        """
        model = EligibilityModule()
        if include_optional:
            return EligibilityModule(
                eligibility_criteria = '',
                healthy_volunteers = True,
                sex = 'FEMALE',
                gender_based = True,
                gender_description = '',
                minimum_age = '4 Month',
                maximum_age = '4 Month',
                std_ages = [
                    'CHILD'
                    ],
                study_population = '',
                sampling_method = 'PROBABILITY_SAMPLE'
            )
        else:
            return EligibilityModule(
        )
        """

    def testEligibilityModule(self):
        """Test EligibilityModule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
